name: Gradle Hero

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-api
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-manager
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-manager-refactored
    - name: Build with Gradle
      run: ./gradlew gD
      working-directory: theme-park-rides
    - name: Build with Gradle
      run: ./gradlew gD
      working-directory: theme-park-rides-kotlin
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-rides-status
    - name: Build with Gradle
      run: ./gradlew gD zD
      working-directory: theme-park-rides-with-zip
    - name: Build with Gradle
      run: ./gradlew gD zD
      working-directory: theme-park-rides-with-zip-fixed      
