name: Gradle Build Bible
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Build theme-park-api
      run: ./gradlew build
      working-directory: theme-park-api
    - name: Build theme-park-manager
      run: ./gradlew build
      working-directory: theme-park-manager
    - name: Build theme-park-manager-refactored
      run: ./gradlew build
      working-directory: theme-park-manager-refactored
    - name: Build theme-park-rides
      run: ./gradlew gD
      working-directory: theme-park-rides
    - name: Build theme-park-rides-status
      run: ./gradlew build
      working-directory: theme-park-rides-status
    - name: Build theme-park-rides-status-extended
      run: ./gradlew build
      working-directory: theme-park-rides-status-extended
    - name: Build theme-park-rides-with-zip
      run: ./gradlew gD && ./gradlew zD
      working-directory: theme-park-rides-with-zip
    - name: Build theme-park-rides-with-zip-fixed
      run: ./gradlew zD
      working-directory: theme-park-rides-with-zip-fixed
    - name: Build file-diff-task
      run: ./gradlew build
      working-directory: file-diff-task
    - name: Build file-diff-plugin
      run: ./gradlew build
      working-directory: file-diff-plugin
    - name: Archive UI
      uses: actions/upload-artifact@v3
      with:
        name: ui
        path: theme-park-manager/ui/build/course-downloadable
        retention-days: 180
    - name: Configure Gradle Build Bible AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::299404798587:role/gradle-build-bible-Role-FATI9KHI61JP
        aws-region: eu-west-1
    - name: Copy downloadable to Gradle Build Bible S3 Bucket
      run: aws s3 cp theme-park-manager/ui/build/ui.zip s3://gradle-hero-website-assets/gradle-build-bible